when:
  event: [push, pull_request, manual]
  branch: main

labels:
  smb: true

steps:
  - name: build-test-lint
    image: node:24
    volumes:
      - pnpm_cache:/root/.local/share/pnpm/store
    when:
      - event: pull_request
    commands:
      - corepack enable
      - corepack prepare pnpm@10 --activate
      - pnpm install --frozen-lockfile
      - pnpm lint
      - pnpm test:coverage
      - cp .env.example .env || true
      - pnpm build

  - name: deploy
    image: node:24
    environment:
      HA_TOKEN:
        from_secret: ha_token
    volumes:
      - pnpm_cache:/root/.local/share/pnpm/store
      - /mnt/homeassistant/overlay:/tmp/mount
    commands:
      - corepack enable
      - corepack prepare pnpm@10 --activate
      - pnpm install --frozen-lockfile
      - pnpm lint
      - pnpm test:coverage
      - cp .env.example .env || true
      - pnpm build
      - cd dist
      - |
        node -e "
        const fs = require('fs');
        const glob = require('glob');
        const token = process.env.HA_TOKEN;
        glob.sync('assets/index-*.js').forEach(file => {
          let content = fs.readFileSync(file, 'utf8');
          content = content.replace(/your_long_lived_access_token_here/g, token);
          fs.writeFileSync(file, content);
        });
        "
      - rm -rf /tmp/mount/*
      - cp -R . /tmp/mount/
    when:
      - event: push
      - event: manual
