when:
  event: [push, pull_request, manual]
  branch: main

steps:
  - name: build-test-lint
    image: node:24
    volumes:
      - pnpm_cache:/root/.local/share/pnpm/store
    when:
      - event: pull_request
    commands:
      - corepack enable
      - corepack prepare pnpm@10 --activate
      - pnpm install --frozen-lockfile
      - pnpm lint
      - pnpm test:coverage
      - cp .env.example .env || true
      - pnpm build

  - name: deploy
    image: node:24
    environment:
      HA_TOKEN:
        from_secret: ha_token
      SMB_SHARE:
        from_secret: smb_share
      SMB_USER:
        from_secret: smb_user
      SMB_PASS:
        from_secret: smb_password
    volumes:
      - pnpm_cache:/root/.local/share/pnpm/store
    commands:
      - corepack enable
      - corepack prepare pnpm@10 --activate
      - pnpm install --frozen-lockfile
      - pnpm lint
      - pnpm test:coverage
      - cp .env.example .env || true
      - pnpm build
      - cd dist
      - printf '%s' "$HA_TOKEN" > /tmp/token.txt
      - cat /tmp/token.txt | head -c 20
      - printf '%s' "$SMB_SHARE" > /tmp/token.txt
      - cat /tmp/token.txt | head -c 20
      - printf '%s' "$SMB_USER" > /tmp/token.txt
      - cat /tmp/token.txt | head -c 20
      - printf '%s' "$SMB_PASS" > /tmp/token.txt
      - cat /tmp/token.txt | head -c 20
      - |
        for file in assets/index-*.js; do
          node -e "const fs=require('fs'); const token=process.env.HA_TOKEN; let c=fs.readFileSync('$file','utf8'); c=c.replace(/your_long_lived_access_token_here/g, token); fs.writeFileSync('$file', c);"
        done

      # Install smbclient
      - apt-get update && apt-get install -y smbclient

      # Delete all files and directories recursively, then upload
      - smbclient //$SMB_SHARE -U "$SMB_USER%$SMB_PASS" -c 'prompt OFF; recurse ON; del *'
      - smbclient //$SMB_SHARE -U "$SMB_USER%$SMB_PASS" -c 'prompt OFF; recurse ON; mput *'
    when:
      - event: push
      - event: manual