when:
  event: [push, pull_request, manual]
  branch: main

labels:
  smb: true

steps:
  - name: build-test-lint
    image: node:24
    volumes:
      - pnpm_cache:/root/.local/share/pnpm/store
    when:
      - event: pull_request
    commands:
      - corepack enable
      - corepack prepare pnpm@10 --activate
      - pnpm install --frozen-lockfile
      - pnpm lint
      - pnpm test:coverage
      - cp .env.example .env || true
      - pnpm build

  - name: deploy
    image: node:24
    environment:
      HA_TOKEN:
        from_secret: ha_token
    volumes:
      - pnpm_cache:/root/.local/share/pnpm/store
      - /mnt/homeassistant/overlay:/tmp/mount
    commands:
      - corepack enable
      - corepack prepare pnpm@10 --activate
      - pnpm install --frozen-lockfile
      - pnpm lint
      - pnpm test:coverage
      - cp .env.example .env || true
      - pnpm build
      - cd dist
      - echo "Direct variable test:"
      - echo "${HA_TOKEN}" > /tmp/token_test.txt
      - cat /tmp/token_test.txt | head -c 30
      - echo "Now trying with sed differently:"
      - TOKEN="${HA_TOKEN}" sed -i "s|your_long_lived_access_token_here|$TOKEN|g" assets/index-*.js || true
      - grep -c "eyJhbGci" assets/index-*.js || echo "Still not found"
      - rm -rf /tmp/mount/*
      - cp -R . /tmp/mount/
    when:
      - event: push
      - event: manual
