when:
  event: [push, pull_request, manual]
  branch: main

labels:
  smb: true

steps:
  - name: build-test-lint
    image: node:24
    volumes:
      - pnpm_cache:/root/.local/share/pnpm/store
    when:
      - event: pull_request
    commands:
      - corepack enable
      - corepack prepare pnpm@10 --activate
      - pnpm install --frozen-lockfile
      - pnpm lint
      - pnpm test:coverage
      - cp .env.example .env || true
      - pnpm build

  - name: deploy
    image: node:24
    environment:
      HA_TOKEN:
        from_secret: ha_token
    volumes:
      - pnpm_cache:/root/.local/share/pnpm/store
      - /mnt/homeassistant/overlay:/tmp/mount
    commands:
      - corepack enable
      - corepack prepare pnpm@10 --activate
      - pnpm install --frozen-lockfile
      - pnpm lint
      - pnpm test:coverage
      - cp .env.example .env || true
      - pnpm build
      - cd dist
      # Write token directly using printf and environment
      - printf '%s' "$HA_TOKEN" > /tmp/token.txt
      - cat /tmp/token.txt | head -c 20
      # Use a simpler approach: let node do the work
      - |
        for file in assets/index-*.js; do
          node -e "const fs=require('fs'); const token=process.env.HA_TOKEN; let c=fs.readFileSync('$file','utf8'); c=c.replace(/your_long_lived_access_token_here/g, token); fs.writeFileSync('$file', c);"
        done
      - rm -rf /tmp/mount/*
      - cp -R . /tmp/mount/
    when:
      - event: push
      - event: manual
