when:
  event: [push, pull_request, manual]
  branch: main

labels:
  smb: true

steps:
  - name: build-test-lint
    image: node:24
    volumes:
      - pnpm_cache:/root/.local/share/pnpm/store
    when:
      - event: pull_request
    commands:
      - corepack enable
      - corepack prepare pnpm@10 --activate
      - pnpm install --frozen-lockfile
      - pnpm lint
      - pnpm test:coverage
      - cp .env.example .env || true
      - pnpm build

  - name: deploy
    image: node:24
    environment:
      HA_TOKEN:
        from_secret: ha_token
    volumes:
      - pnpm_cache:/root/.local/share/pnpm/store
      - /mnt/homeassistant/overlay:/tmp/mount
    commands:
      - corepack enable
      - corepack prepare pnpm@10 --activate
      - pnpm install --frozen-lockfile
      - pnpm lint
      - pnpm test:coverage
      - cp .env.example .env || true
      - pnpm build
      - cd dist
      - echo "Testing HA_TOKEN"
      - echo "$HA_TOKEN" | head -c 20
      - echo "About to run sed..."
      - sed -i "s|your_long_lived_access_token_here|${HA_TOKEN}|g" assets/index-*.js || true
      - echo "Checking result:"
      - grep -o ".{0,20}your_long_lived_access_token_here.{0,20}" assets/index-*.js || echo "Pattern not found (good - means replacement worked)"
      - echo "Verifying token in file"
      - grep -c "eyJhbGci" assets/index-*.js || echo "Token pattern not found in file"
      - rm -rf /tmp/mount/*
      - cp -R . /tmp/mount/
    when:
      - event: push
      - event: manual
